---
- hosts: db
  become: true
  vars:
    mongo_version: "4.4"
    mongo_data_dir: "/data/db"
  tasks:
  - name: Add MongoDB repo key
    rpm_key:
      state: present
      key: "https://www.mongodb.org/static/pgp/server-{{ mongo_version }}.asc"
  - name: Add MongoDB repo
    yum_repository:
      name: mongodb-org-{{ mongo_version }}
      description: MongoDB Repository
      baseurl: https://repo.mongodb.org/yum/redhat/$releasever/mongodb-org/{{ mongo_version }}/x86_64/
      gpgcheck: true
      enabled: true
      gpgkey: "https://www.mongodb.org/static/pgp/server-{{ mongo_version }}.asc"
  - name: Install MongoDB
    yum:
      name: mongodb-org
      state: present
  - name: Create MongoDB data directory
    file:
      path: "{{ mongo_data_dir }}"
      state: directory
  - name: Modify MongoDB configuration file
    lineinfile:
      path: /etc/mongod.conf
      regexp: "^dbPath"
      line: "dbPath={{ mongo_data_dir }}"
      state: present
  - name: Start MongoDB
    systemd:
      name: mongod
      state: started
      enabled: true

